Multiple call to import
deprecate/metal-soy-critic pull request #14
Opened 2017-12-22 23:31 UTC by carloslancha

This resolves https://github.com/metal/metal-soy-critic/issues/13

Btw, first time with Typescript so... 😛

2017-12-24 01:17 UTC, mthadley requested changes
@carloslancha These changes are really nice! 👍 

Just a few style nitpicks and I think it should be good to go.

2017-12-24 01:17 UTC, mthadley commented on src/config.ts
> +type CallToImportConfig = {
Generally, it's better to prefer interfaces over type alias for this kind of thing.

2017-12-24 01:17 UTC, mthadley commented on src/config.ts
> +  for (let i=0; i < config.callToImport.length; i++) {
Prefer `for of` over c-style loops:
```ts
for (const item of config.callToImport) {
  /* ... */
}
```

2017-12-24 01:17 UTC, mthadley commented on src/config.ts
> +    console.log(chalk.yellow('CONFIG API HAS CHANGED, PLEASE UPDATE\n'));
💯

2017-12-24 01:17 UTC, mthadley commented on src/validate-call-imports.ts
> +      for (let i=0; i < config.callToImport.length; i++) {
Same as above, try using a `for of` instead.

2017-12-26 11:42 UTC, jbalsas commented
Nice job, @carloslancha! 

/cc @mthadley, since he might not be aware of your latest push!

2017-12-26 17:30 UTC, mthadley approved these changes

2017-12-26 17:30 UTC, merged